### ISSUE TITLE
Warning with every video in console

### ISSUE THREAD

**Issue by Xyronius** [gabireze/tiktok-all-favorite-videos-remover#2]
Whenever it tries to unfavorite a video it says [Starling ICU Warning] The interpolation parameter "{number}" is missing in the translation text "Like video
{number} likes" for the key "accessibilityLabels_forYou_btn_like"
Suggestions: check whether the value is null or undefined. Try using empty string '' as fallback! e.g I18n.t('key', { apple: count || '' })

I have had it running multiple times and it sometimes just skips unfavoriting videos even though I have done the steps as needed. Had it running for about 12 hours total already and it only unfavorited about 400 videos even tough if all went well it should delete 1 per 3 seconds  which would be 14400 videos. 

Any fix for this?

**Comment by gabireze** [comment]
The error you mentioned (and in the screenshot below) occurs when opening any TikTok video through the web version. I uninstalled my browser extension and tested it to check if it was related, but it was not. It seems to be an internal UI error on TikTok's front end.

![image](https://github.com/gabireze/tiktok-all-favorite-videos-remover/assets/31194373/753cba45-57a8-4d6d-98bd-a9b7b0deaf9b)

I tested this with a list of 10 TikTok videos in my favorites. It took about 50 seconds to start the process, delete the videos, and close the tab. I set this 3-second interval because sometimes it takes a while for the video to load, depending on the user's internet.

If the video doesn't load properly, the process won't proceed with removing it from favorites. Instead, it will move to the next video and continue the process.

I've created a 1-minute video that demonstrates the persistent occurrence of the error even when the browser extension isn't in use. Additionally, I've provided a walk-through of the extension's functionality. You can observe the extension's messages in the browser's console, specifically within the "Info" section of the "Console" tab.

This ensures that only the extension's messages are showcased, even if errors arise. Toward the end of the video, I intentionally induced this behavior to display the messages in a formatted manner.

This will help you ascertain that the error is indeed originating from the extension itself and not from any other section of the page.

https://github.com/gabireze/tiktok-all-favorite-videos-remover/assets/31194373/093bc0ab-a711-4f01-bb45-d64f755ac304

If the extension doesn't work as expected on Google Chrome, you might want to try using it on Mozilla Firefox or Microsoft Edge. Both browsers support the extension. I came across another user who mentioned that the extension wasn't working on Chrome, but they were able to use it seamlessly on Edge. I always make sure to test the extension on these three browsers before releasing it. I test both the local version and the version from the Chrome extensions store to ensure they're both correct.

**Comment by Xyronius** [comment]
Alright, I tried on Chrome first but after I saw the comment of the other person that said that Edge worked better I started using Edge. All videos do load in as I have the browser open just for best results and to verify they are loading but if I check back after some time I see that not all were unfavorited. Good that the error is not because of the extension though. 

I will just try again and see what it does and otherwise I just have to do it a lot of times.


Thanks for the quick response!
